# config linter: https://lint.travis-ci.org/

language: python
python:
    - 2.7
    - 3.3
    - 3.4
install:
    - pip install coverage coveralls pylint
    - python setup.py install --install-headers "${VIRTUAL_ENV}"/include/snakeoil
script:
    - pushd build/lib*
    - coverage run --source snakeoil -m py.test
    - coverage report
after_success:
    # upload coverage data to coveralls.io
    - coveralls
    - popd

    # run pylint checks
    - if [[ ${TRAVIS_PYTHON_VERSION} == 3* ]]; then 2to3 -wn lintplugin/*.py; fi
    - ./pylint -f colorized --reports y build/lib*/snakeoil
