language: python
python:
  - 2.7
  - 3.4
  - 3.5
matrix:
  fast_finish: true
  allow_failures:
    - python: nightly
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
install: pip install tox coveralls codecov
script: tox -e travis
after_success:
  # upload coverage data
  - pushd .tox/travis/lib/python*/site-packages
  - coveralls
  - codecov
  - popd
